version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - cd front-end
      - npm install
  pre_build:
      commands:
      - echo "Creating .env file from environment variables..."
      - echo "VITE_SUPABASE_KEY=$VITE_SUPABASE_KEY" > .env
      - echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> .env
      - echo "THIRDWEB_CLIENT_ID=$THIRDWEB_CLIENT_ID">> .env

  build:
    commands:
      - echo "Building the React/Vite app..."
      - npm run build

  post_build:
    commands:
      - echo "Clearing old files in S3 bucket..."
      - aws s3 rm s3://www.imarahub.xyz --recursive
      - echo "Uploading new build to S3..."
      - aws s3 cp dist/ s3://www.imarahub.xyz/ --recursive
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: front-end/dist
